import Head from "next/head";
import Navbar from "~/components/Navbar"
import { useSession } from "next-auth/react";

export default function Workouts() {
  const { data:sessionData } = useSession()
 
  return (
    <>
      <Head>
        <title>Your Dashboard - TCW</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="img/png" href="/favicon.png" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-background-50">
        <Navbar/>
        {sessionData?.user ? 
          <h1>Welcome back, {sessionData.user.name}!</h1>
          :
          <h1>Please Sign In</h1>
        }
      </main>
    </>
  );
}

