import Head from "next/head";
import Navbar from "~/components/Navbar"
import { useSession } from "next-auth/react";

export default function Workouts() {
  const { data:sessionData } = useSession()
 
  return (
    <>
      <Head>
        <title>Your Dashboard - TCW</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="img/png" href="/favicon.png" />
      </Head>
      <main className="min-h-screen bg-background">
        <Navbar/>
        { sessionData?.user ? 
          <div className="container flex flex-col justify-center p-5 gap-5">
            <div className="rounded-lg p-5 shadow-sm bg-background-100">
              <h1 className="text-text text-2xl font-semibold">
                Welcome back {sessionData.user.name}!
              </h1>
              <span>Your Last workout was on </span>
            </div>
            <div className="rounded-lg p-5 shadow-sm bg-primary-100">
              <h1 className="text-text text-2xl font-semibold">
                Workouts
              </h1>
            </div>
            <div className="rounded-lg p-5 shadow-sm bg-secondary-100">
              <h1 className="text-text text-2xl font-semibold">
                Welcome back {sessionData.user.name}!
              </h1>
              <span>Your Last workout was on </span>
            </div>
          </div>
          :
          <div className="min-h-screen flex items-center justify-center">Please Sign In</div>
        }
      </main>
    </>
  );
}

