import Head from "next/head";
import { api } from "~/utils/api";
import Navbar from "~/components/Navbar"

export default function Workouts() {
  // const { data: workouts } = api.workout.getAll.useQuery()
  const { data: test } = api.workout.getSomething.useQuery()
  console.log(test)
 
  return (
    <>
      <Head>
        <title>Tristan&apos;s Charity Workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="img/png" href="/favicon.png" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-background-50">
        <Navbar/>
        <div className="container flex flex-col items-left m-auto justify-center gap-12 px-4 py-16">
          <div className="flex flex-col items-left gap-2">
            Tristan&apos;s Charity Workouts
          </div>
        </div>
      </main>
    </>
  );
}

