import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import WelcomeHeader from "~/components/WelcomeHeader"

export default function Workouts() {
  // const { data: workouts } = api.workout.getAll.useQuery()
  const { data: test } = api.workout.getSomething.useQuery()
  console.log(test)
 
  return (
    <>
      <Head>
        <title>Zaroc&apos;s Charity Workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-background-50">
        <div className="container flex flex-col items-left justify-center gap-12 px-4 py-16 ">

          <h1 className="text-5xl font-extrabold tracking-tight text-49 sm:text-[5rem]">
            Zaroc&apos;s Charity Workouts
          </h1>

          <div className="flex flex-col items-left gap-2">
            <WelcomeHeader/>
          </div>


        </div>
      </main>
    </>
  );
}

