// import Navbar from "./Navbar"
import WelcomeHeader from "./WelcomeHeader"
import Head from "next/head"

export default function WorkoutLayout ( {children } ) {
  return (
    <>
      <Head>
        <title>Zaroc&apos;s Charity Workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-left justify-center gap-12 px-4 py-16 ">

          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Zaroc&apos;s Charity Workouts
          </h1>
          <WelcomeHeader/>
        </div>

        {children}
      </main>
    </>
  )
}

