import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import WelcomeHeader from "~/components/WelcomeHeader"

export default function Workouts() {
  const { data: workouts, refetch: refetchWorkouts } = api.workout.getAll.useQuery()

  return (
    <>
      <Head>
        <title>Zaroc's Charity Workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-left justify-center gap-12 px-4 py-16 ">

          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Zaroc's Charity Workouts
          </h1>

          <div className="flex flex-col items-left gap-2">
            <WelcomeHeader/>
          </div>

          <h1 className="text-3xl font-semibold text-white">Your Past Workouts</h1>
          {workouts?.map((workout) => {
             return (
              <Link key={workout.id}
                href={`/workouts/${workout.id}`}
                className="rounded bg-white px-4 py-4">
                Workout on {workout.created_at.toDateString()}
              </Link>
             )
            })
          }

          <div className="flex items-center gap-3">
            <Link
              href="/workouts/new"
              className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
            >
              Add Workout
            </Link>
          </div>

        </div>
      </main>
    </>
  );
}

